### ISSUE TITLE
Configuration of basic conformance classes is missing

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wps20#18]
The basic conformance classes must be configured in https://github.com/opengeospatial/ets-wps20/blob/main/src/main/config/teamengine/config.xml.

**Comment by ghobona** [comment]
We are putting this Issue on hold, so that we can look into whether testng can run the following logic:

```
IF basictests==pass && sync==pass  THEN certify
ELSE IF basictests==pass && async==pass  THEN certify
ELSE fail
```

Note that passing the `basictests` by themselves **does not** mean the product can be certified

**Comment by dstenger** [comment]
Currently, an if else logic is not possible when configuring basic conformance classes.

Thus, we decided during CITE meeting (2023-01-04) that no basic conformance classes are configured.
Instead, the documentation is enhanced explaining both combinations possible for certification.

**Comment by dstenger** [comment]
Files to be modified:
* https://github.com/opengeospatial/ets-wps20/blob/main/src/site/asciidoc/index.adoc
* https://github.com/opengeospatial/ets-wps20/blob/main/src/main/scripts/ctl/wps20-suite.ctl

**Comment by dstenger** [comment]
Issue for enhancing the documentation was created: #26
