### ISSUE TITLE
Collect test/demo services

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wps20#2]

**Comment by ghobona** [comment]
The list of implementations is at https://www.ogc.org/resource/products/uncertified?&specid=698

**Comment by ghobona** [comment]
52 North Demo service http://geoprocessing.demo.52north.org

WPS 2.0 demo service http://geoprocessing.demo.52north.org:8080/javaps/service?Request=GetCapabilities&Service=WPS

The demo service is maintained by @bpross-52n

**Comment by dstenger** [comment]
Please check: http://geoprocessing.demo.52north.org:8080/javaps/service?Request=GetCapabilities&Service=WPS

**Comment by ghobona** [comment]
CubeWerx WPS 

https://cubewerx.pvretano.com/cubewerx/cubeserv?SERVICE=WPS&Request=GetCapabilities

https://eratosthenes.pvretano.com/cubewerx/cubeserv?SERVICE=WPS&REQUEST=GetCapabilities&ACCEPTVERSIONS=2.0.0

The demo service is maintained by @pvretano

**Comment by pvretano** [comment]
One caveat with regard to the pvretano.com servers mentioned by @ghobona .  This is my development machine so the server may, at any given time, be down or not working depending on what development work I am doing.  If you run any issue please feel free to contact me at pvretano[at]cubewerx.com and I will try to resolve your issue ASAP.
