### ISSUE TITLE
Implement Synchronous WPS (Conformance Class)

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wps20#3]
Please see http://docs.opengeospatial.org/is/14-065/14-065.html#94 for details.

**Comment by arieslai** [comment]
Remove the example request xml, and implement the test with echo process only.

**Comment by ghobona** [comment]
2021-11-17 @arieslai to focus on A.2 (synchronous WPS) next.

**Comment by ghobona** [comment]
Tests needing to be completed for A.2

- [x] A.5.1
- [x] A.5.2
- [x] A.5.3
- [x] A.5.4
- [x] A.5.5
- [x] A.5.6
- [x] A.5.7
- [x] A.5.8
- [x] A.5.9 and/or A.5.16
- [x] A.5.10 and/or A.5.17
- [x] A.5.11
- [x] A.5.13
