### ISSUE TITLE
Issue with service not named org.n52.javaps.test.EchoProcess 

### ISSUE THREAD

**Issue by gfenoy** [opengeospatial/ets-wps20#31]
**Describe the bug**
When running the ETS the following tests are failing in case the service is not identified as `org.n52.javaps.test.EchoProcess` or no input is identified as `literalInput` or no output is identified as `literalOutput` :

 * ValidInputDataTranmissionByValue
 * ValidOutDataTranmissionByValue
 * ValidInputDataTranmissionByReference
 * ValidOutDataTranmissionByReference

In other words, the template is read and used as-is with no modification.

**To Reproduce**
Run the ETS against any instance with an echo service identified with `org.n52.javaps.test.EchoProcess1`, or with an input identified as `literalInput1`,  or with an output identified as `literalOutput1`. The tests listed here will fail.
Run the test again and use an IUT providing a service with the original name (`org.n52.javaps.test.EchoProcess`), more tests will succeed.

**Expected behavior**
Having the request always corresponding to the echo service provided by the IUT. In other words, having the template rewritten in the corresponding java methods using the same logic used in `ValidEchoProcess`.

**Comment by ghobona** [comment]
@gfenoy Please provide the URL of the endpoint that you were trying to test, so that we can reproduce the issue.

**Comment by gfenoy** [comment]
@ghobona we have setup these two Server Instances:

 * http://tb17.geolabs.fr:8120/cgi-bin/zoo_loader.cgi (SI1)
 * http://tb17.geolabs.fr:8121/cgi-bin/zoo_loader.cgi (SI2)

The two instances are the exact same version of the software. The first one exposes a service named `org.n52.javaps.test.EchoProcess`, with the required inputs and output names as in the one exposed on the default IUT. The second one have the exact same services with the echo service named `echo` and inputs named `a`, `b` and `c`.

Using the [online ETS](https://cite.opengeospatial.org/te2/) with one Server Instance or another should give the exact same result, but you can find bellow the current results.

* SI1: Pass: 14	Fail: 3	Skip: 0	Total tests: 17
* SI2: Pass: 11	Fail: 6	Skip: 0	Total tests: 17

**Comment by ghobona** [comment]
@gfenoy Could you please confirm that (apart from the process name) SI1 and SI2 share the exact same code?

**Comment by arieslai** [comment]
@gfenoy SI2 is failing with this request. This request is generated by test suite in the test ValidOutDataTranmissionByReference.
```
<?xml version="1.0" encoding="UTF-8"?>
<wps:Execute xmlns:wps="http://www.opengis.net/wps/2.0"
             xmlns:ows="http://www.opengis.net/ows/2.0"
             xmlns:xlink="http://www.w3.org/1999/xlink"
             xmlns:xsi="http://www.aw3.org/2001/XMLSchema-instance"
             mode="sync"
             response="document"
             service="WPS"
             version="2.0.0"
             xsi:schemaLocation="http://www.opengis.net/wps/2.0 ../wps.xsd">
      <ows:Identifier>echo</ows:Identifier>
      <wps:Input id="a">
            <wps:Reference mimeType="text/plain"
                     xlink:href="https://raw.githubusercontent.com/opengeospatial/ets-wps20/main/src/main/resources/org/opengis/cite/wps20/examples/vehicle.txt"/>
      </wps:Input>
      <wps:Output id="a" transmission="reference"/>
</wps:Execute>
```

**Comment by arieslai** [comment]
@gfenoy SI2 is failing with this request too. This request is generated by test suite in the test ValidInputDataTranmissionByReference.
```
<?xml version="1.0" encoding="UTF-8"?>
<wps:Execute xmlns:wps="http://www.opengis.net/wps/2.0"
             xmlns:ows="http://www.opengis.net/ows/2.0"
             xmlns:xlink="http://www.w3.org/1999/xlink"
             xmlns:xsi="http://www.aw3.org/2001/XMLSchema-instance"
             mode="sync"
             response="document"
             service="WPS"
             version="2.0.0"
             xsi:schemaLocation="http://www.opengis.net/wps/2.0 ../wps.xsd">
      <ows:Identifier>echo</ows:Identifier>
      <wps:Input id="a">
            <wps:Reference mimeType="text/plain"
                     xlink:href="https://raw.githubusercontent.com/opengeospatial/ets-wps20/main/src/main/resources/org/opengis/cite/wps20/examples/vehicle.txt"/>
      </wps:Input>
      <wps:Output id="a" transmission="value"/>
</wps:Execute>
```

**Comment by gfenoy** [comment]
@arieslai thanks for your report.

We have setup a new Server Instance available here:

http://tb17.geolabs.fr:8122/cgi-bin/zoo_loader.cgi 

It should solve the issues reported about the two requests.

**Comment by gfenoy** [comment]
> @gfenoy Could you please confirm that (apart from the process name) SI1 and SI2 share the exact same code?

Unfortunately, the Server Instance SI2 has been modified over time during our testing.

I can setup another Server Instance based on the latest published SI (http://tb17.geolabs.fr:8122/cgi-bin/zoo_loader.cgi, which contains both services ```org.n52.javaps.test.EchoProcess``` and ```echo```), if it helps.

Please let me know.

**Comment by ghobona** [comment]
@gfenoy We encountered an issue with the `echo` process whereby it duplicates the mimeType attribute. 

We are also getting status 500 errors from the WPS when we send some requests to the `echo` process.

@arieslai will post the requests and responses below.

**Comment by arieslai** [comment]
@gfenoy, here's the table of the result running with the test suite in this branch.
https://github.com/opengeospatial/ets-wps20/tree/fix_for_issue_31_33

|            |                                      | org.n52.javaps.test.EchoProcess                                     | echo                         |
|------------|--------------------------------------|---------------------------------------------------------------------|------------------------------|
| BasicTests | ValidAsyncExcecuteViaPOSTXML         | PASS                                                                |                          500 |
| BasicTests | ValidAutoExcecuteViaPOSTXML          | PASS                                                                |                          500 |
| BasicTests | ValidInputDataTranmissionByReference | duplicate mimeType attribute                                        | duplicate mimeType attribute |
| BasicTests | ValidOutDataTranmissionByReference   | duplicate mimeType attribute                                        | duplicate mimeType attribute |
| AsyncTests | ValidGetResultViaGETKVP              | response status always running                                      | 500                          |
| AsyncTests | ValidGetResultViaPOSTXML             | First send async response="raw" post. Then send GetStatus. Last GetResult receives   404 | 500                          |
| AsyncTests | ValidGetStatusViaGETKVP              | PASS                                                                | 500                          |
| AsyncTests | ValidGetResultViaPOSTXML             | PASS                                                                | 500                          |

**Comment by arieslai** [comment]
Here are the xml post requests that cause 500 with ECHO_PROCESS_ID=echo:
async post request response="raw"
```xml
<?xml version="1.0" encoding="UTF-8"?>
<wps:Execute xmlns:wps="http://www.opengis.net/wps/2.0"
             xmlns:ows="http://www.opengis.net/ows/2.0"
             xmlns:xlink="http://www.w3.org/1999/xlink"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             mode="async"
             response="raw"
             service="WPS"
             version="2.0.0"
             xsi:schemaLocation="http://www.opengis.net/wps/2.0 http://schemas.opengis.net/wps/2.0/wps.xsd">
    <ows:Identifier>echo</ows:Identifier>
	  <wps:Input id="a">
        <wps:Data>
            <wps:LiteralValue>hello_literal</wps:LiteralValue>
        </wps:Data>
    </wps:Input>
	  <wps:Output id="a" transmission="value"/>
</wps:Execute>
```

async post request response="document"
```xml
<?xml version="1.0" encoding="UTF-8"?>
<wps:Execute xmlns:wps="http://www.opengis.net/wps/2.0"
             xmlns:ows="http://www.opengis.net/ows/2.0"
             xmlns:xlink="http://www.w3.org/1999/xlink"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             mode="async"
             response="document"
             service="WPS"
             version="2.0.0"
             xsi:schemaLocation="http://www.opengis.net/wps/2.0 http://schemas.opengis.net/wps/2.0/wps.xsd">
    <ows:Identifier>echo</ows:Identifier>
	  <wps:Input id="a">
        <wps:Data>
            <wps:LiteralValue>hello_literal</wps:LiteralValue>
        </wps:Data>
    </wps:Input>
	  <wps:Output id="a" transmission="value"/>
</wps:Execute>
```

**Comment by arieslai** [comment]
Here is the xml post request and response with duplicate mimeType with both ECHO_PROCESS_ID:

sync post request with ECHO_PROCESS_ID=echo
```xml
<?xml version="1.0" encoding="UTF-8"?>
<wps:Execute xmlns:wps="http://www.opengis.net/wps/2.0"
             xmlns:ows="http://www.opengis.net/ows/2.0"
             xmlns:xlink="http://www.w3.org/1999/xlink"
             xmlns:xsi="http://www.aw3.org/2001/XMLSchema-instance"
             mode="sync"
             response="document"
             service="WPS"
             version="2.0.0"
             xsi:schemaLocation="http://www.opengis.net/wps/2.0 ../wps.xsd">
      <ows:Identifier>echo</ows:Identifier>
      <wps:Input id="a">
            <wps:Reference mimeType="text/plain"
                     xlink:href="https://raw.githubusercontent.com/opengeospatial/ets-wps20/main/src/main/resources/org/opengis/cite/wps20/examples/vehicle.txt"/>
      </wps:Input>
      <wps:Output id="a" transmission="value"/>
</wps:Execute>
```

response
```xml
<?xml version="1.0" encoding="utf-8"?>
<wps:Result xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:wps="http://www.opengis.net/wps/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wps/2.0 http://schemas.opengis.net/wps/2.0/wps.xsd">
  <wps:Output id="a">
    <wps:Data mimeType="text/plain" mimeType="text/plain">car
</wps:Data>
  </wps:Output>
</wps:Result>
```

**Comment by arieslai** [comment]
For the status is always Running(instead of Succeeded) in the test ValidGetResultViaGETKVP, and response 404 in test ValidGetResultViaPOSTXML, it is tested with ECHO_PROCESS_ID=org.n52.javaps.test.EchoProcess. Here are the related 3 requests:

1. async post request response="raw"
```xml
<?xml version="1.0" encoding="UTF-8"?>
<wps:Execute xmlns:wps="http://www.opengis.net/wps/2.0"
             xmlns:ows="http://www.opengis.net/ows/2.0"
             xmlns:xlink="http://www.w3.org/1999/xlink"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             mode="async"
             response="raw"
             service="WPS"
             version="2.0.0"
             xsi:schemaLocation="http://www.opengis.net/wps/2.0 http://schemas.opengis.net/wps/2.0/wps.xsd">
    <ows:Identifier>org.n52.javaps.test.EchoProcess</ows:Identifier>
	  <wps:Input id="literalInput">
        <wps:Data>
            <wps:LiteralValue>hello_literal</wps:LiteralValue>
        </wps:Data>
    </wps:Input>
	  <wps:Output id="literalOutput" transmission="value"/>
</wps:Execute>
```

2. Then send GetStatus.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<wps:StatusInfo xmlns:wps="http://www.opengis.net/wps/2.0"
                xmlns:ows="http://www.opengis.net/ows/2.0"
                xmlns:xlink="http://www.w3.org/1999/xlink"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://www.opengis.net/wps/2.0 http://schemas.opengis.net/wps/2.0/wps.xsd">
  <wps:JobID>634e3132-1036-11ee-8ab1-0242ac108009</wps:JobID>
  <wps:Status>Accepted</wps:Status>
</wps:StatusInfo>
```

3. Last send GetResult.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<wps:GetResult xmlns:wps="http://www.opengis.net/wps/2.0"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               service="WPS"
               version="2.0.0"
               xsi:schemaLocation="http://www.opengis.net/wps/2.0 ../wps.xsd">
	
	  <wps:JobID>634e3132-1036-11ee-8ab1-0242ac108009</wps:JobID>
	
</wps:GetResult>
```

After GetResult We'll receive http status code 404.
```xml
<?xml version="1.0" encoding="utf-8"?>
<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ows/2.0 http://schemas.opengis.net/ows/2.0/owsExceptionReport.xsd" xml:lang="en-US" version="2.0.2">
    <ows:Exception exceptionCode="ResultNotReady" locator="634e3132-1036-11ee-8ab1-0242ac108009">
        <ows:ExceptionText>The result for the requested JobID has not yet been generated. The service is currently running.</ows:ExceptionText>
    </ows:Exception>
</ows:ExceptionReport>
```

**Comment by ghobona** [comment]
This Issue will be closed on 2024-03-30 if there is no further action or response.
