### ISSUE TITLE
Why using a not found URL when passing input by reference

### ISSUE THREAD

**Issue by gfenoy** [opengeospatial/ets-wps20#33]
**Describe the bug**
To pass the `ValidInputDataTranmissionByReference` test, it is required that IUT supports 404 as an acceptable status code when downloading a reference. Indeed, the file used as a template (https://github.com/opengeospatial/ets-wps20/blob/main/src/main/resources/org/opengis/cite/wps20/examples/ValidInputReference.xml) to provide an input by reference uses an URL which return 404.

**To Reproduce**
Run the ETS.

**Expected behavior**
Using a found URL (200) as reference for testing execution properly.
In case the input reference returns a 404, I think that the IUT should return an exception with a 400 status code.

**Comment by ghobona** [comment]
@gfenoy We will change the URL in the example to reference an XML document that exists.
