### ISSUE TITLE
Output message when running the test suite: Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by arieslai** [opengeospatial/ets-wps20#38]
**Describe the bug**
Output message showing SLF4J error:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**To Reproduce**
1. Run the test suite on Eclipse. 
2. The message will show in the Console tab.

**Expected behavior**
Although the message is shown, the test suite still runs successfully. Currently not sure what is missing.

**Screenshots**
Run with Eclipse. 
![image](https://github.com/opengeospatial/ets-wps20/assets/50437972/d6b9d0d9-172e-4afb-8beb-4920eb006355)

Run with command: mvn clean install site -Dsource=8 -Pintegration-tests,docker
![image](https://github.com/opengeospatial/ets-wps20/assets/50437972/b74c8f49-8c74-4718-b363-67f145305584)

**Comment by dstenger** [comment]
The error can be reproduced when starting TEAM Engine with Tomcat (see logs), e.g. by using the Dockerfile of this repository.

However, this error also occurs with other test suites (e.g. ets-wfs20):
```
0a8a2e> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
0a8a2e> SLF4J: Defaulting to no-operation (NOP) logger implementation
0a8a2e> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

Thus, it does not prevent an installation on Beta as it does not affect the functionality of the test suite but just logging.

However, the root cause should still be found and fixed.

**Comment by dstenger** [comment]
On Beta and Production the logging is working.
Also, locally there are log messages printed.

Documentation about this warning on slf4j website: https://www.slf4j.org/codes.html#StaticLoggerBinder

Adding following dependency removes the warnings:
```
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-nop</artifactId>
      <version>1.7.20</version>
    </dependency>
```

Logging still seems to work.

**Comment by arieslai** [comment]
The error message does not effect the logging functionality of the test suite. Since this error also occurs with other test suites (e.g. ets-wfs20), we will close the issue.
