### ISSUE TITLE
Invalid README build steps

### ISSUE THREAD

**Issue by fmigneault** [opengeospatial/ets-wps20#40]
**Describe the bug**

After successfully running the steps up to `mvn package`, the resulting jar is generated in `./ets-wps20/target/ets-wps20-0.4-SNAPSHOT.jar` (instead of `./ets-wps20/ets-wps20-0.4-SNAPSHOT.jar` as mentioned in the README). The following Docker build command fails because it cannot find the JAR in the right location. 

**To Reproduce**
Follow the build steps of the README.

The main problem seems related to the part: 

> `cd /docker`
> Build the docker image.
> `docker build -t wps20:local . `

I cannot find any other "docker" reference than https://github.com/opengeospatial/ets-wps20/tree/main/src/docker, which does not contain any of the expected build results.

The command produices the following error:
```shell 

❯ docker build -t wps20:local .
[+] Building 0.4s (6/15)                                                                                                                                          docker:default
 => [internal] load build definition from Dockerfile                                                                                                                        0.0s
 => => transferring dockerfile: 926B                                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                           0.0s
 => => transferring context: 2B                                                                                                                                             0.0s
 => [internal] load metadata for docker.io/library/tomcat:7.0-jre8                                                                                                          0.4s
 => CACHED [ 1/11] FROM docker.io/library/tomcat:7.0-jre8@sha256:3d6475354578a0b083f2e91700dcb8a1275dc5f574435276ce0ec69be588d6a3                                           0.0s
 => [internal] load build context                                                                                                                                           0.0s
 => => transferring context: 2B                                                                                                                                             0.0s
 => ERROR [ 2/11] ADD maven/dependency/teamengine-web-*.war /root/                                                                                                          0.0s
------
 > [ 2/11] ADD maven/dependency/teamengine-web-*.war /root/:
------
Dockerfile:4
--------------------
   2 |     
   3 |     # add TEAM engine webapp
   4 | >>> ADD maven/dependency/teamengine-web-*.war /root/
   5 |     RUN cd /root/ && unzip -q teamengine-web-*.war -d /usr/local/tomcat/webapps/teamengine
   6 |     
--------------------
ERROR: failed to solve: lstat /var/lib/docker/tmp/buildkit-mount2758450932/maven/dependency: no such file or directory
```

**Expected behavior**
Everything build and files are found automatically where expected.

**Additional context**
```
❯ mvn -v
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.20, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_CA, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-82-generic", arch: "amd64", family: "unix"
```

**Comment by dstenger** [comment]
Thank you for reporting.
You are right, the documentation seems to be outdated here.
Please check this manual: https://github.com/opengeospatial/cite/wiki/How-to-create-Docker-Images-of-test-suites#create-docker-image-and-create-and-start-docker-container? Could you please provide feedback if this solves your problem? Then, I will update the README.

**Comment by fmigneault** [comment]
Yes. This procedure worked. I was able to start the docker after using `docker run -p 9090:8080 ogccite/ets-wps20:latest` with the application responding on `http://localhost:9090/teamengine`. 

I tried running the ETS WPS2.0 tests suite after. 
My test server is here: https://services.crim.ca/weaver/wps?service=WPS&request=GetCapabilities, with the `echo` process responding here: https://services.crim.ca/weaver/wps?service=WPS&request=DescribeProcess&identifier=echo&f=xml. 

I have tried running the tests with the input `https://services.crim.ca/weaver/wps` as the URL, but all tests except 1 (Valid Service Name) fail. Is this the correct value to provide?

**Comment by dstenger** [comment]
Yes, the input should be correct.
It seems that your service does not support version 2.0.0.
When I request https://services.crim.ca/weaver/wps?service=WPS&request=GetCapabilities&version=2.0.0, I still get a WPS 1.0.0 capabilities document.
Can you please check this?
If you have further questions about the testing of your specific service, can you please open a new GitHub issue (this issue should only discuss the README topic)?

**Comment by fmigneault** [comment]
Thanks for point out this problem!
Beside the invalid schema locations (`http://www.opengis.net/wps/1.0.0`), is there something obvious that seems to be missing in the XML output to make it WPS-2.0.0 compliant?
I will forward the relevant details to the maintainers for the underlying WPS server.

**Comment by dstenger** [comment]
PR was created to remove the outdated content: #41
